[[redirects]]
  from = "/old-page.html"
  to = "/new-page.html"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5001/api/:splat"
  status = 200

[[redirects]]
  from = "/gotoshopping*"
  to = "http://localhost:3000/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
